apiVersion: v1
kind: Service
metadata:
  name: my-service
  namespace: test-commands
spec:
  type: NodePort
  selector:
    app: MyApp
  ports:
    - port: 80
      targetPort: 80
      nodePort: 30007
